name: CI-CD Pokemon API

on:
  push:
    branches:
      - main

jobs:
  testes:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar Poetry
        run: pip install poetry

      - name: Instalar dependencias
        run: poetry install

      - name: Rodar testes
        run: poetry run pytest

      - name: Build Docker
        run: docker build -t pokemon-api .
